# Training configuration for drug response prediction model

# Data settings
data_dir: "personalized_drug_ai/data"
dataset_file: "processed/drug_response_dataset.csv"
train_ratio: 0.8

# Model settings
genetic_model_name: "dmis-lab/biobert-base-cased-v1.1"
drug_model_name: "Downloads/DrugBERT"
num_response_classes: 5
genetic_embedding_dim: 768
drug_embedding_dim: 768
fusion_hidden_dim: 512

# Training settings
seed: 42
batch_size: 32
num_workers: 4
max_epochs: 20
learning_rate: 1e-5
weight_decay: 0.01
dropout_rate: 0.2
patience: 10
log_every_n_steps: 50

# Output settings
output_dir: "personalized_drug_ai/results/model_training" 